### PR TITLE
Bridge Extra IRC Events: QUIT, KICK, TOPIC, MODE #33

### PR DESCRIPTION
**Pull request by Zarthus**
Adds bridging of KICK, QUIT

Optionally bridge TOPIC, MODE with the `announce-extras` config

- Note: TOPIC relaying is partially bugged due to race conditions in this version of KICL, upgrade to get it fixed. https://kitteh.org/2019/03/23/kicl-710-released/

Also fixes a typo in a file name

Feel free to cherry pick specific changes you're interested in. I'm not sure why the CI is failing.

### CODE REVIEW

**Comment by Zarthus** [comment]
@zachbr 
topic bridging is already behind a config option that's off by default (`announce-extras`)

**Comment by zachbr** [comment]
You are entirely correct on that. I just glanced right over that.

**Comment by Zarthus** [comment]
@zachbr So what are the next steps?

**Comment by zachbr** [comment]
Just gotta test and merge at this point. Should be soon.

**Comment by Zarthus** [comment]
sidenote: Logging your own quit may be useful to determine if the bridge bot died.

**Comment by zachbr** [comment]
Thanks :)

**Pull request merged**
